# Generated by Django 4.1.5 on 2023-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
